# Data Preprocessing

## Importing Libs

In [1]:
import numpy as np

import pandas as pd
import tensorflow as tf

2025-07-11 09:15:26.489568: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
tf.__version__

'2.12.0'

## Importing Dataset and Creating Dataset

In [3]:

df = pd.read_csv('/Users/harmansingh/AI Engineering/Machine Learning/Basic Deep Learning/Artificial Neural Networks (ANN)/Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
x= df.iloc[:,3:-1].values
y= df.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding Categorical Data

### Label Encoding of Gender

In [7]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding on Geography

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
cl = ColumnTransformer( transformers = [('encoder',OneHotEncoder(),[1])], remainder = 'passthrough' )
x= np.array(cl.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting Of Dataset

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Building ANN

## Initialize the ANN

In [11]:
ann = tf.keras.models.Sequential()

2025-07-11 09:15:37.812783: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2025-07-11 09:15:37.813611: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-07-11 09:15:37.813644: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-07-11 09:15:37.814268: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-07-11 09:15:37.814358: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


## Adding Input Layer and First Hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

## Adding 2nd Hidden Layer

In [13]:
ann.add( tf.keras.layers.Dense( units=6,activation = 'relu' ) )

## Adding Output Layer

In [14]:
ann.add( tf.keras.layers.Dense( units=1,activation = 'sigmoid' ) )

# Training The ANN

## Compiling ANN

In [15]:
ann.compile( optimizer = 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'] )


## Training ANN

In [16]:
ann.fit(x_train,y_train, batch_size=32, epochs =100)

Epoch 1/100


2025-07-11 09:15:49.572120: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2025-07-11 09:15:49.608418: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_10.


250/250 [==============================] - 2s 4ms/step - loss: 0.5990 - accuracy: 0.6821
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7993
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4364 - accuracy: 0.8046
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.8075
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.8067
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.8087
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.8091
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.8085
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.8104
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.8084
E

# Making The Prediction and Evaluating The Model

## Predicting The Single Observation 

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

2025-07-11 09:18:54.034258: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 1s 570ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

## Predicting Test Set Result

In [18]:
y_pred= ann.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [19]:
y_pred= (y_pred>0.5)
print(np.concatenate(( y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1) ),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score

In [22]:
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:',cm)
print()
print('Accuracy:', accuracy_score(y_test,y_pred) )
print()
print( 'Precision:',precision_score(y_test,y_pred) )
print()
print( 'Recall:',recall_score(y_test,y_pred) )
print()
print( 'F1_score:',f1_score(y_test,y_pred) )

Confusion Matrix: [[1482  113]
 [ 264  141]]

Accuracy: 0.8115

Precision: 0.5551181102362205

Recall: 0.34814814814814815

F1_score: 0.4279210925644917
